version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: fe57
      MYSQL_DATABASE: app
  app:
    build:
      context: .
    ports:
      - "80:80"
    depends_on:
      - db